-- migration: up 

INSERT INTO especies (id,name) VALUES (1, 'Seed Pokémon');
INSERT INTO especies (id,name) VALUES (2, 'Lizard Pokémon');
INSERT INTO especies (id,name) VALUES (3, 'Flame Pokémon');
INSERT INTO especies (id,name) VALUES (4, 'Tiny Turtle Pokémon');
INSERT INTO especies (id,name) VALUES (5, 'Turtle Pokémon');
INSERT INTO especies (id,name) VALUES (6, 'Shellfish Pokémon');
INSERT INTO especies (id,name) VALUES (7, 'Worm Pokémon');
INSERT INTO especies (id,name) VALUES (8, 'Cocoon Pokémon');
INSERT INTO especies (id,name) VALUES (9, 'Butterfly Pokémon');
INSERT INTO especies (id,name) VALUES (10, 'Hairy Bug Pokémon');
INSERT INTO especies (id,name) VALUES (11, 'Poison Bee Pokémon');
INSERT INTO especies (id,name) VALUES (12, 'Tiny Bird Pokémon');
INSERT INTO especies (id,name) VALUES (13, 'Bird Pokémon');
INSERT INTO especies (id,name) VALUES (14, 'Mouse Pokémon');
INSERT INTO especies (id,name) VALUES (15, 'Beak Pokémon');
INSERT INTO especies (id,name) VALUES (16, 'Snake Pokémon');
INSERT INTO especies (id,name) VALUES (17, 'Cobra Pokémon');
INSERT INTO especies (id,name) VALUES (18, 'Poison Pin Pokémon');
INSERT INTO especies (id,name) VALUES (19, 'Drill Pokémon');
INSERT INTO especies (id,name) VALUES (20, 'Fairy Pokémon');
INSERT INTO especies (id,name) VALUES (21, 'Fox Pokémon');
INSERT INTO especies (id,name) VALUES (22, 'Balloon Pokémon');
INSERT INTO especies (id,name) VALUES (23, 'Bat Pokémon');
INSERT INTO especies (id,name) VALUES (24, 'Weed Pokémon');
INSERT INTO especies (id,name) VALUES (25, 'Flower Pokémon');
INSERT INTO especies (id,name) VALUES (26, 'Mushroom Pokémon');
INSERT INTO especies (id,name) VALUES (27, 'Insect Pokémon');
INSERT INTO especies (id,name) VALUES (28, 'Poison Moth Pokémon');
INSERT INTO especies (id,name) VALUES (29, 'Mole Pokémon');
INSERT INTO especies (id,name) VALUES (30, 'Scratch Cat Pokémon');
INSERT INTO especies (id,name) VALUES (31, 'Classy Cat Pokémon');
INSERT INTO especies (id,name) VALUES (32, 'Duck Pokémon');
INSERT INTO especies (id,name) VALUES (33, 'Pig Monkey Pokémon');
INSERT INTO especies (id,name) VALUES (34, 'Puppy Pokémon');
INSERT INTO especies (id,name) VALUES (35, 'Legendary Pokémon');
INSERT INTO especies (id,name) VALUES (36, 'Tadpole Pokémon');
INSERT INTO especies (id,name) VALUES (37, 'Psi Pokémon');
INSERT INTO especies (id,name) VALUES (38, 'Superpower Pokémon');
INSERT INTO especies (id,name) VALUES (39, 'Flycatcher Pokémon');
INSERT INTO especies (id,name) VALUES (40, 'Jellyfish Pokémon');
INSERT INTO especies (id,name) VALUES (41, 'Rock Pokémon');
INSERT INTO especies (id,name) VALUES (42, 'Megaton Pokémon');
INSERT INTO especies (id,name) VALUES (43, 'Fire Horse Pokémon');
INSERT INTO especies (id,name) VALUES (44, 'Unique Horn Pokémon');
INSERT INTO especies (id,name) VALUES (45, 'Dopey Pokémon');
INSERT INTO especies (id,name) VALUES (46, 'Hermit Crab Pokémon');
INSERT INTO especies (id,name) VALUES (47, 'Magnet Pokémon');
INSERT INTO especies (id,name) VALUES (48, 'Wild Duck Pokémon');
INSERT INTO especies (id,name) VALUES (49, 'Twin Bird Pokémon');
INSERT INTO especies (id,name) VALUES (50, 'Triple Bird Pokémon');
INSERT INTO especies (id,name) VALUES (51, 'Sea Lion Pokémon');
INSERT INTO especies (id,name) VALUES (52, 'Sludge Pokémon');
INSERT INTO especies (id,name) VALUES (53, 'Bivalve Pokémon');
INSERT INTO especies (id,name) VALUES (54, 'Gas Pokémon');
INSERT INTO especies (id,name) VALUES (55, 'Shadow Pokémon');
INSERT INTO especies (id,name) VALUES (56, 'Rock Snake Pokémon');
INSERT INTO especies (id,name) VALUES (57, 'Hypnosis Pokémon');
INSERT INTO especies (id,name) VALUES (58, 'River Crab Pokémon');
INSERT INTO especies (id,name) VALUES (59, 'Pincer Pokémon');
INSERT INTO especies (id,name) VALUES (60, 'Ball Pokémon');
INSERT INTO especies (id,name) VALUES (61, 'Egg Pokémon');
INSERT INTO especies (id,name) VALUES (62, 'Coconut Pokémon');
INSERT INTO especies (id,name) VALUES (63, 'Lonely Pokémon');
INSERT INTO especies (id,name) VALUES (64, 'Bone Keeper Pokémon');
INSERT INTO especies (id,name) VALUES (65, 'Kicking Pokémon');
INSERT INTO especies (id,name) VALUES (66, 'Punching Pokémon');
INSERT INTO especies (id,name) VALUES (67, 'Licking Pokémon');
INSERT INTO especies (id,name) VALUES (68, 'Poison Gas Pokémon');
INSERT INTO especies (id,name) VALUES (69, 'Spikes Pokémon');
INSERT INTO especies (id,name) VALUES (70, 'Vine Pokémon');
INSERT INTO especies (id,name) VALUES (71, 'Parent Pokémon');
INSERT INTO especies (id,name) VALUES (72, 'Dragon Pokémon');
INSERT INTO especies (id,name) VALUES (73, 'Goldfish Pokémon');
INSERT INTO especies (id,name) VALUES (74, 'Star Shape Pokémon');
INSERT INTO especies (id,name) VALUES (75, 'Mysterious Pokémon');
INSERT INTO especies (id,name) VALUES (76, 'Barrier Pokémon');
INSERT INTO especies (id,name) VALUES (77, 'Dancing Pokémon');
INSERT INTO especies (id,name) VALUES (78, 'Mantis Pokémon');
INSERT INTO especies (id,name) VALUES (79, 'Human Shape Pokémon');
INSERT INTO especies (id,name) VALUES (80, 'Electric Pokémon');
INSERT INTO especies (id,name) VALUES (81, 'Spitfire Pokémon');
INSERT INTO especies (id,name) VALUES (82, 'Stag Beetle Pokémon');
INSERT INTO especies (id,name) VALUES (83, 'Wild Bull Pokémon');
INSERT INTO especies (id,name) VALUES (84, 'Fish Pokémon');
INSERT INTO especies (id,name) VALUES (85, 'Atrocious Pokémon');
INSERT INTO especies (id,name) VALUES (86, 'Transport Pokémon');
INSERT INTO especies (id,name) VALUES (87, 'Transform Pokémon');
INSERT INTO especies (id,name) VALUES (88, 'Evolution Pokémon');
INSERT INTO especies (id,name) VALUES (89, 'Bubble Jet Pokémon');
INSERT INTO especies (id,name) VALUES (90, 'Lightning Pokémon');
INSERT INTO especies (id,name) VALUES (91, 'Virtual Pokémon');
INSERT INTO especies (id,name) VALUES (92, 'Spiral Pokémon');
INSERT INTO especies (id,name) VALUES (93, 'Fossil Pokémon');
INSERT INTO especies (id,name) VALUES (94, 'Sleeping Pokémon');
INSERT INTO especies (id,name) VALUES (95, 'Freeze Pokémon');
INSERT INTO especies (id,name) VALUES (96, 'Cruel Pokémon');
INSERT INTO especies (id,name) VALUES (97, 'Strong Legs Pokémon');
INSERT INTO especies (id,name) VALUES (98, 'Malevolent Pokémon');
INSERT INTO especies (id,name) VALUES (99, 'Genetic Pokémon');
INSERT INTO especies (id,name) VALUES (100, 'New Species Pokémon');
INSERT INTO especies (id,name) VALUES (101, 'Leaf Pokémon');
INSERT INTO especies (id,name) VALUES (102, 'Herb Pokémon');
INSERT INTO especies (id,name) VALUES (103, 'Fire Mouse Pokémon');
INSERT INTO especies (id,name) VALUES (104, 'Volcano Pokémon');
INSERT INTO especies (id,name) VALUES (105, 'Big Jaw Pokémon');
INSERT INTO especies (id,name) VALUES (106, 'Scout Pokémon');
INSERT INTO especies (id,name) VALUES (107, 'Long Body Pokémon');
INSERT INTO especies (id,name) VALUES (108, 'Owl Pokémon');
INSERT INTO especies (id,name) VALUES (109, 'Five Star Pokémon');
INSERT INTO especies (id,name) VALUES (110, 'String Spit Pokémon');
INSERT INTO especies (id,name) VALUES (111, 'Long Leg Pokémon');
INSERT INTO especies (id,name) VALUES (112, 'Angler Pokémon');
INSERT INTO especies (id,name) VALUES (113, 'Light Pokémon');
INSERT INTO especies (id,name) VALUES (114, 'Tiny Mouse Pokémon');
INSERT INTO especies (id,name) VALUES (115, 'Spike Ball Pokémon');
INSERT INTO especies (id,name) VALUES (116, 'Happiness Pokémon');
INSERT INTO especies (id,name) VALUES (117, 'Mystic Pokémon');
INSERT INTO especies (id,name) VALUES (118, 'Wool Pokémon');
INSERT INTO especies (id,name) VALUES (119, 'Aqua Mouse Pokémon');
INSERT INTO especies (id,name) VALUES (120, 'Aqua Rabbit Pokémon');
INSERT INTO especies (id,name) VALUES (121, 'Imitation Pokémon');
INSERT INTO especies (id,name) VALUES (122, 'Frog Pokémon');
INSERT INTO especies (id,name) VALUES (123, 'Cottonweed Pokémon');
INSERT INTO especies (id,name) VALUES (124, 'Long Tail Pokémon');
INSERT INTO especies (id,name) VALUES (125, 'Sun Pokémon');
INSERT INTO especies (id,name) VALUES (126, 'Clear Wing Pokémon');
INSERT INTO especies (id,name) VALUES (127, 'Water Fish Pokémon');
INSERT INTO especies (id,name) VALUES (128, 'Moonlight Pokémon');
INSERT INTO especies (id,name) VALUES (129, 'Darkness Pokémon');
INSERT INTO especies (id,name) VALUES (130, 'Royal Pokémon');
INSERT INTO especies (id,name) VALUES (131, 'Hexpert Pokémon');
INSERT INTO especies (id,name) VALUES (132, 'Screech Pokémon');
INSERT INTO especies (id,name) VALUES (133, 'Symbol Pokémon');
INSERT INTO especies (id,name) VALUES (134, 'Patient Pokémon');
INSERT INTO especies (id,name) VALUES (135, 'Long Neck Pokémon');
INSERT INTO especies (id,name) VALUES (136, 'Bagworm Pokémon');
INSERT INTO especies (id,name) VALUES (137, 'Land Snake Pokémon');
INSERT INTO especies (id,name) VALUES (138, 'FlyScorpion Pokémon');
INSERT INTO especies (id,name) VALUES (139, 'Iron Snake Pokémon');
INSERT INTO especies (id,name) VALUES (140, 'Mold Pokémon');
INSERT INTO especies (id,name) VALUES (141, 'Single Horn Pokémon');
INSERT INTO especies (id,name) VALUES (142, 'Sharp Claw Pokémon');
INSERT INTO especies (id,name) VALUES (143, 'Little Bear Pokémon');
INSERT INTO especies (id,name) VALUES (144, 'Hibernator Pokémon');
INSERT INTO especies (id,name) VALUES (145, 'Lava Pokémon');
INSERT INTO especies (id,name) VALUES (146, 'Pig Pokémon');
INSERT INTO especies (id,name) VALUES (147, 'Swine Pokémon');
INSERT INTO especies (id,name) VALUES (148, 'Coral Pokémon');
INSERT INTO especies (id,name) VALUES (149, 'Jet Pokémon');
INSERT INTO especies (id,name) VALUES (150, 'Delivery Pokémon');
INSERT INTO especies (id,name) VALUES (151, 'Kite Pokémon');
INSERT INTO especies (id,name) VALUES (152, 'Armor Bird Pokémon');
INSERT INTO especies (id,name) VALUES (153, 'Dark Pokémon');
INSERT INTO especies (id,name) VALUES (154, 'Long Nose Pokémon');
INSERT INTO especies (id,name) VALUES (155, 'Armor Pokémon');
INSERT INTO especies (id,name) VALUES (156, 'Big Horn Pokémon');
INSERT INTO especies (id,name) VALUES (157, 'Painter Pokémon');
INSERT INTO especies (id,name) VALUES (158, 'Scuffle Pokémon');
INSERT INTO especies (id,name) VALUES (159, 'Handstand Pokémon');
INSERT INTO especies (id,name) VALUES (160, 'Kiss Pokémon');
INSERT INTO especies (id,name) VALUES (161, 'Live Coal Pokémon');
INSERT INTO especies (id,name) VALUES (162, 'Milk Cow Pokémon');
INSERT INTO especies (id,name) VALUES (163, 'Thunder Pokémon');
INSERT INTO especies (id,name) VALUES (164, 'Aurora Pokémon');
INSERT INTO especies (id,name) VALUES (165, 'Rock Skin Pokémon');
INSERT INTO especies (id,name) VALUES (166, 'Hard Shell Pokémon');
INSERT INTO especies (id,name) VALUES (167, 'Diving Pokémon');
INSERT INTO especies (id,name) VALUES (168, 'Rainbow Pokémon');
INSERT INTO especies (id,name) VALUES (169, 'Time Travel Pokémon');
INSERT INTO especies (id,name) VALUES (170, 'Wood Gecko Pokémon');
INSERT INTO especies (id,name) VALUES (171, 'Forest Pokémon');
INSERT INTO especies (id,name) VALUES (172, 'Chick Pokémon');
INSERT INTO especies (id,name) VALUES (173, 'Young Fowl Pokémon');
INSERT INTO especies (id,name) VALUES (174, 'Blaze Pokémon');
INSERT INTO especies (id,name) VALUES (175, 'Mud Fish Pokémon');
INSERT INTO especies (id,name) VALUES (176, 'Bite Pokémon');
INSERT INTO especies (id,name) VALUES (177, 'TinyRaccoon Pokémon');
INSERT INTO especies (id,name) VALUES (178, 'Tiny Raccoon Pokémon');
INSERT INTO especies (id,name) VALUES (179, 'Rushing Pokémon');
INSERT INTO especies (id,name) VALUES (180, 'Water Weed Pokémon');
INSERT INTO especies (id,name) VALUES (181, 'Jolly Pokémon');
INSERT INTO especies (id,name) VALUES (182, 'Carefree Pokémon');
INSERT INTO especies (id,name) VALUES (183, 'Acorn Pokémon');
INSERT INTO especies (id,name) VALUES (184, 'Wily Pokémon');
INSERT INTO especies (id,name) VALUES (185, 'Wicked Pokémon');
INSERT INTO especies (id,name) VALUES (186, 'TinySwallow Pokémon');
INSERT INTO especies (id,name) VALUES (187, 'Swallow Pokémon');
INSERT INTO especies (id,name) VALUES (188, 'Seagull Pokémon');
INSERT INTO especies (id,name) VALUES (189, 'Water Bird Pokémon');
INSERT INTO especies (id,name) VALUES (190, 'Feeling Pokémon');
INSERT INTO especies (id,name) VALUES (191, 'Emotion Pokémon');
INSERT INTO especies (id,name) VALUES (192, 'Embrace Pokémon');
INSERT INTO especies (id,name) VALUES (193, 'Pond Skater Pokémon');
INSERT INTO especies (id,name) VALUES (194, 'Eyeball Pokémon');
INSERT INTO especies (id,name) VALUES (195, 'Slacker Pokémon');
INSERT INTO especies (id,name) VALUES (196, 'Wild Monkey Pokémon');
INSERT INTO especies (id,name) VALUES (197, 'Lazy Pokémon');
INSERT INTO especies (id,name) VALUES (198, 'Trainee Pokémon');
INSERT INTO especies (id,name) VALUES (199, 'Ninja Pokémon');
INSERT INTO especies (id,name) VALUES (200, 'Shed Pokémon');
INSERT INTO especies (id,name) VALUES (201, 'Whisper Pokémon');
INSERT INTO especies (id,name) VALUES (202, 'Big Voice Pokémon');
INSERT INTO especies (id,name) VALUES (203, 'Loud Noise Pokémon');
INSERT INTO especies (id,name) VALUES (204, 'Guts Pokémon');
INSERT INTO especies (id,name) VALUES (205, 'Arm Thrust Pokémon');
INSERT INTO especies (id,name) VALUES (206, 'Polka Dot Pokémon');
INSERT INTO especies (id,name) VALUES (207, 'Compass Pokémon');
INSERT INTO especies (id,name) VALUES (208, 'Kitten Pokémon');
INSERT INTO especies (id,name) VALUES (209, 'Prim Pokémon');
INSERT INTO especies (id,name) VALUES (210, 'Deceiver Pokémon');
INSERT INTO especies (id,name) VALUES (211, 'Iron Armor Pokémon');
INSERT INTO especies (id,name) VALUES (212, 'Meditate Pokémon');
INSERT INTO especies (id,name) VALUES (213, 'Discharge Pokémon');
INSERT INTO especies (id,name) VALUES (214, 'Cheering Pokémon');
INSERT INTO especies (id,name) VALUES (215, 'Firefly Pokémon');
INSERT INTO especies (id,name) VALUES (216, 'Thorn Pokémon');
INSERT INTO especies (id,name) VALUES (217, 'Stomach Pokémon');
INSERT INTO especies (id,name) VALUES (218, 'Poison Bag Pokémon');
INSERT INTO especies (id,name) VALUES (219, 'Savage Pokémon');
INSERT INTO especies (id,name) VALUES (220, 'Brutal Pokémon');
INSERT INTO especies (id,name) VALUES (221, 'Ball Whale Pokémon');
INSERT INTO especies (id,name) VALUES (222, 'Float Whale Pokémon');
INSERT INTO especies (id,name) VALUES (223, 'Numb Pokémon');
INSERT INTO especies (id,name) VALUES (224, 'Eruption Pokémon');
INSERT INTO especies (id,name) VALUES (225, 'Coal Pokémon');
INSERT INTO especies (id,name) VALUES (226, 'Bounce Pokémon');
INSERT INTO especies (id,name) VALUES (227, 'Manipulate Pokémon');
INSERT INTO especies (id,name) VALUES (228, 'Spot Panda Pokémon');
INSERT INTO especies (id,name) VALUES (229, 'Ant Pit Pokémon');
INSERT INTO especies (id,name) VALUES (230, 'Vibration Pokémon');
INSERT INTO especies (id,name) VALUES (231, 'Cactus Pokémon');
INSERT INTO especies (id,name) VALUES (232, 'Scarecrow Pokémon');
INSERT INTO especies (id,name) VALUES (233, 'Cotton Bird Pokémon');
INSERT INTO especies (id,name) VALUES (234, 'Humming Pokémon');
INSERT INTO especies (id,name) VALUES (235, 'Cat Ferret Pokémon');
INSERT INTO especies (id,name) VALUES (236, 'Fang Snake Pokémon');
INSERT INTO especies (id,name) VALUES (237, 'Meteorite Pokémon');
INSERT INTO especies (id,name) VALUES (238, 'Whiskers Pokémon');
INSERT INTO especies (id,name) VALUES (239, 'Ruffian Pokémon');
INSERT INTO especies (id,name) VALUES (240, 'Rogue Pokémon');
INSERT INTO especies (id,name) VALUES (241, 'Clay Doll Pokémon');
INSERT INTO especies (id,name) VALUES (242, 'Sea Lily Pokémon');
INSERT INTO especies (id,name) VALUES (243, 'Barnacle Pokémon');
INSERT INTO especies (id,name) VALUES (244, 'Old Shrimp Pokémon');
INSERT INTO especies (id,name) VALUES (245, 'Plate Pokémon');
INSERT INTO especies (id,name) VALUES (246, 'Tender Pokémon');
INSERT INTO especies (id,name) VALUES (247, 'Weather Pokémon');
INSERT INTO especies (id,name) VALUES (248, 'Color Swap Pokémon');
INSERT INTO especies (id,name) VALUES (249, 'Puppet Pokémon');
INSERT INTO especies (id,name) VALUES (250, 'Marionette Pokémon');
INSERT INTO especies (id,name) VALUES (251, 'Requiem Pokémon');
INSERT INTO especies (id,name) VALUES (252, 'Beckon Pokémon');
INSERT INTO especies (id,name) VALUES (253, 'Fruit Pokémon');
INSERT INTO especies (id,name) VALUES (254, 'Wind Chime Pokémon');
INSERT INTO especies (id,name) VALUES (255, 'Disaster Pokémon');
INSERT INTO especies (id,name) VALUES (256, 'Bright Pokémon');
INSERT INTO especies (id,name) VALUES (257, 'Snow Hat Pokémon');
INSERT INTO especies (id,name) VALUES (258, 'Face Pokémon');
INSERT INTO especies (id,name) VALUES (259, 'Clap Pokémon');
INSERT INTO especies (id,name) VALUES (260, 'Ball Roll Pokémon');
INSERT INTO especies (id,name) VALUES (261, 'Ice Break Pokémon');
INSERT INTO especies (id,name) VALUES (262, 'Deep Sea Pokémon');
INSERT INTO especies (id,name) VALUES (263, 'South Sea Pokémon');
INSERT INTO especies (id,name) VALUES (264, 'Longevity Pokémon');
INSERT INTO especies (id,name) VALUES (265, 'Rendezvous Pokémon');
INSERT INTO especies (id,name) VALUES (266, 'Rock Head Pokémon');
INSERT INTO especies (id,name) VALUES (267, 'Endurance Pokémon');
INSERT INTO especies (id,name) VALUES (268, 'Iron Ball Pokémon');
INSERT INTO especies (id,name) VALUES (269, 'Iron Claw Pokémon');
INSERT INTO especies (id,name) VALUES (270, 'Iron Leg Pokémon');
INSERT INTO especies (id,name) VALUES (271, 'Rock Peak Pokémon');
INSERT INTO especies (id,name) VALUES (272, 'Iceberg Pokémon');
INSERT INTO especies (id,name) VALUES (273, 'Iron Pokémon');
INSERT INTO especies (id,name) VALUES (274, 'Eon Pokémon');
INSERT INTO especies (id,name) VALUES (275, 'Sea Basin Pokémon');
INSERT INTO especies (id,name) VALUES (276, 'Continent Pokémon');
INSERT INTO especies (id,name) VALUES (277, 'Sky High Pokémon');
INSERT INTO especies (id,name) VALUES (278, 'Wish Pokémon');
INSERT INTO especies (id,name) VALUES (279, 'DNA Pokémon');
INSERT INTO especies (id,name) VALUES (280, 'Tiny Leaf Pokémon');
INSERT INTO especies (id,name) VALUES (281, 'Grove Pokémon');
INSERT INTO especies (id,name) VALUES (282, 'Chimp Pokémon');
INSERT INTO especies (id,name) VALUES (283, 'Playful Pokémon');
INSERT INTO especies (id,name) VALUES (284, 'Penguin Pokémon');
INSERT INTO especies (id,name) VALUES (285, 'Emperor Pokémon');
INSERT INTO especies (id,name) VALUES (286, 'Starling Pokémon');
INSERT INTO especies (id,name) VALUES (287, 'Predator Pokémon');
INSERT INTO especies (id,name) VALUES (288, 'Plump Mouse Pokémon');
INSERT INTO especies (id,name) VALUES (289, 'Beaver Pokémon');
INSERT INTO especies (id,name) VALUES (290, 'Cricket Pokémon');
INSERT INTO especies (id,name) VALUES (291, 'Flash Pokémon');
INSERT INTO especies (id,name) VALUES (292, 'Spark Pokémon');
INSERT INTO especies (id,name) VALUES (293, 'Gleam Eyes Pokémon');
INSERT INTO especies (id,name) VALUES (294, 'Bud Pokémon');
INSERT INTO especies (id,name) VALUES (295, 'Bouquet Pokémon');
INSERT INTO especies (id,name) VALUES (296, 'Head Butt Pokémon');
INSERT INTO especies (id,name) VALUES (297, 'Shield Pokémon');
INSERT INTO especies (id,name) VALUES (298, 'Moth Pokémon');
INSERT INTO especies (id,name) VALUES (299, 'Tiny Bee Pokémon');
INSERT INTO especies (id,name) VALUES (300, 'Beehive Pokémon');
INSERT INTO especies (id,name) VALUES (301, 'EleSquirrel Pokémon');
INSERT INTO especies (id,name) VALUES (302, 'Sea Weasel Pokémon');
INSERT INTO especies (id,name) VALUES (303, 'Cherry Pokémon');
INSERT INTO especies (id,name) VALUES (304, 'Blossom Pokémon');
INSERT INTO especies (id,name) VALUES (305, 'Sea Slug Pokémon');
INSERT INTO especies (id,name) VALUES (306, 'Blimp Pokémon');
INSERT INTO especies (id,name) VALUES (307, 'Rabbit Pokémon');
INSERT INTO especies (id,name) VALUES (308, 'Magical Pokémon');
INSERT INTO especies (id,name) VALUES (309, 'Big Boss Pokémon');
INSERT INTO especies (id,name) VALUES (310, 'Catty Pokémon');
INSERT INTO especies (id,name) VALUES (311, 'Tiger Cat Pokémon');
INSERT INTO especies (id,name) VALUES (312, 'Bell Pokémon');
INSERT INTO especies (id,name) VALUES (313, 'Skunk Pokémon');
INSERT INTO especies (id,name) VALUES (314, 'Bronze Pokémon');
INSERT INTO especies (id,name) VALUES (315, 'Bronze Bell Pokémon');
INSERT INTO especies (id,name) VALUES (316, 'Bonsai Pokémon');
INSERT INTO especies (id,name) VALUES (317, 'Mime Pokémon');
INSERT INTO especies (id,name) VALUES (318, 'Playhouse Pokémon');
INSERT INTO especies (id,name) VALUES (319, 'Music Note Pokémon');
INSERT INTO especies (id,name) VALUES (320, 'Forbidden Pokémon');
INSERT INTO especies (id,name) VALUES (321, 'Land Shark Pokémon');
INSERT INTO especies (id,name) VALUES (322, 'Cave Pokémon');
INSERT INTO especies (id,name) VALUES (323, 'Mach Pokémon');
INSERT INTO especies (id,name) VALUES (324, 'Big Eater Pokémon');
INSERT INTO especies (id,name) VALUES (325, 'Emanation Pokémon');
INSERT INTO especies (id,name) VALUES (326, 'Aura Pokémon');
INSERT INTO especies (id,name) VALUES (327, 'Hippo Pokémon');
INSERT INTO especies (id,name) VALUES (328, 'Heavyweight Pokémon');
INSERT INTO especies (id,name) VALUES (329, 'Scorpion Pokémon');
INSERT INTO especies (id,name) VALUES (330, 'Ogre Scorp Pokémon');
INSERT INTO especies (id,name) VALUES (331, 'Toxic Mouth Pokémon');
INSERT INTO especies (id,name) VALUES (332, 'Bug Catcher Pokémon');
INSERT INTO especies (id,name) VALUES (333, 'Wing Fish Pokémon');
INSERT INTO especies (id,name) VALUES (334, 'Neon Pokémon');
INSERT INTO especies (id,name) VALUES (335, 'Frost Tree Pokémon');
INSERT INTO especies (id,name) VALUES (336, 'Magnet Area Pokémon');
INSERT INTO especies (id,name) VALUES (337, 'Thunderbolt Pokémon');
INSERT INTO especies (id,name) VALUES (338, 'Blast Pokémon');
INSERT INTO especies (id,name) VALUES (339, 'Jubilee Pokémon');
INSERT INTO especies (id,name) VALUES (340, 'Ogre Darner Pokémon');
INSERT INTO especies (id,name) VALUES (341, 'Verdant Pokémon');
INSERT INTO especies (id,name) VALUES (342, 'Fresh Snow Pokémon');
INSERT INTO especies (id,name) VALUES (343, 'Fang Scorp Pokémon');
INSERT INTO especies (id,name) VALUES (344, 'Twin Tusk Pokémon');
INSERT INTO especies (id,name) VALUES (345, 'Blade Pokémon');
INSERT INTO especies (id,name) VALUES (346, 'Gripper Pokémon');
INSERT INTO especies (id,name) VALUES (347, 'Snow Land Pokémon');
INSERT INTO especies (id,name) VALUES (348, 'Plasma Pokémon');
INSERT INTO especies (id,name) VALUES (349, 'Knowledge Pokémon');
INSERT INTO especies (id,name) VALUES (350, 'Willpower Pokémon');
INSERT INTO especies (id,name) VALUES (351, 'Temporal Pokémon');
INSERT INTO especies (id,name) VALUES (352, 'Spatial Pokémon');
INSERT INTO especies (id,name) VALUES (353, 'Lava Dome Pokémon');
INSERT INTO especies (id,name) VALUES (354, 'Colossal Pokémon');
INSERT INTO especies (id,name) VALUES (355, 'Renegade Pokémon');
INSERT INTO especies (id,name) VALUES (356, 'Lunar Pokémon');
INSERT INTO especies (id,name) VALUES (357, 'Sea Drifter Pokémon');
INSERT INTO especies (id,name) VALUES (358, 'Seafaring Pokémon');
INSERT INTO especies (id,name) VALUES (359, 'Pitch-Black Pokémon');
INSERT INTO especies (id,name) VALUES (360, 'Gratitude Pokémon');
INSERT INTO especies (id,name) VALUES (361, 'Alpha Pokémon');
INSERT INTO especies (id,name) VALUES (362, 'Victory Pokémon');
INSERT INTO especies (id,name) VALUES (363, 'Grass Snake Pokémon');
INSERT INTO especies (id,name) VALUES (364, 'Regal Pokémon');
INSERT INTO especies (id,name) VALUES (365, 'Fire Pig Pokémon');
INSERT INTO especies (id,name) VALUES (366, 'Mega Fire Pig Pokémon');
INSERT INTO especies (id,name) VALUES (367, 'Sea Otter Pokémon');
INSERT INTO especies (id,name) VALUES (368, 'Discipline Pokémon');
INSERT INTO especies (id,name) VALUES (369, 'Formidable Pokémon');
INSERT INTO especies (id,name) VALUES (370, 'Lookout Pokémon');
INSERT INTO especies (id,name) VALUES (371, 'Loyal Dog Pokémon');
INSERT INTO especies (id,name) VALUES (372, 'Big-Hearted Pokémon');
INSERT INTO especies (id,name) VALUES (373, 'Devious Pokémon');
INSERT INTO especies (id,name) VALUES (374, 'Grass Monkey Pokémon');
INSERT INTO especies (id,name) VALUES (375, 'Thorn Monkey Pokémon');
INSERT INTO especies (id,name) VALUES (376, 'High Temp Pokémon');
INSERT INTO especies (id,name) VALUES (377, 'Ember Pokémon');
INSERT INTO especies (id,name) VALUES (378, 'Spray Pokémon');
INSERT INTO especies (id,name) VALUES (379, 'Geyser Pokémon');
INSERT INTO especies (id,name) VALUES (380, 'Dream Eater Pokémon');
INSERT INTO especies (id,name) VALUES (381, 'Drowsing Pokémon');
INSERT INTO especies (id,name) VALUES (382, 'Tiny Pigeon Pokémon');
INSERT INTO especies (id,name) VALUES (383, 'Wild Pigeon Pokémon');
INSERT INTO especies (id,name) VALUES (384, 'Proud Pokémon');
INSERT INTO especies (id,name) VALUES (385, 'Electrified Pokémon');
INSERT INTO especies (id,name) VALUES (386, 'Mantle Pokémon');
INSERT INTO especies (id,name) VALUES (387, 'Ore Pokémon');
INSERT INTO especies (id,name) VALUES (388, 'Compressed Pokémon');
INSERT INTO especies (id,name) VALUES (389, 'Courting Pokémon');
INSERT INTO especies (id,name) VALUES (390, 'Subterrene Pokémon');
INSERT INTO especies (id,name) VALUES (391, 'Hearing Pokémon');
INSERT INTO especies (id,name) VALUES (392, 'Muscular Pokémon');
INSERT INTO especies (id,name) VALUES (393, 'Judo Pokémon');
INSERT INTO especies (id,name) VALUES (394, 'Karate Pokémon');
INSERT INTO especies (id,name) VALUES (395, 'Sewing Pokémon');
INSERT INTO especies (id,name) VALUES (396, 'Leaf-Wrapped Pokémon');
INSERT INTO especies (id,name) VALUES (397, 'Nurturing Pokémon');
INSERT INTO especies (id,name) VALUES (398, 'Centipede Pokémon');
INSERT INTO especies (id,name) VALUES (399, 'Curlipede Pokémon');
INSERT INTO especies (id,name) VALUES (400, 'Megapede Pokémon');
INSERT INTO especies (id,name) VALUES (401, 'Cotton Puff Pokémon');
INSERT INTO especies (id,name) VALUES (402, 'Windveiled Pokémon');
INSERT INTO especies (id,name) VALUES (403, 'Bulb Pokémon');
INSERT INTO especies (id,name) VALUES (404, 'Flowering Pokémon');
INSERT INTO especies (id,name) VALUES (405, 'Hostile Pokémon');
INSERT INTO especies (id,name) VALUES (406, 'Desert Croc Pokémon');
INSERT INTO especies (id,name) VALUES (407, 'Intimidation Pokémon');
INSERT INTO especies (id,name) VALUES (408, 'Zen Charm Pokémon');
INSERT INTO especies (id,name) VALUES (409, 'Blazing Pokémon');
INSERT INTO especies (id,name) VALUES (410, 'Rock Inn Pokémon');
INSERT INTO especies (id,name) VALUES (411, 'Stone Home Pokémon');
INSERT INTO especies (id,name) VALUES (412, 'Shedding Pokémon');
INSERT INTO especies (id,name) VALUES (413, 'Hoodlum Pokémon');
INSERT INTO especies (id,name) VALUES (414, 'Avianoid Pokémon');
INSERT INTO especies (id,name) VALUES (415, 'Spirit Pokémon');
INSERT INTO especies (id,name) VALUES (416, 'Coffin Pokémon');
INSERT INTO especies (id,name) VALUES (417, 'Prototurtle Pokémon');
INSERT INTO especies (id,name) VALUES (418, 'First Bird Pokémon');
INSERT INTO especies (id,name) VALUES (419, 'Trash Bag Pokémon');
INSERT INTO especies (id,name) VALUES (420, 'Trash Heap Pokémon');
INSERT INTO especies (id,name) VALUES (421, 'Tricky Fox Pokémon');
INSERT INTO especies (id,name) VALUES (422, 'Illusion Fox Pokémon');
INSERT INTO especies (id,name) VALUES (423, 'Chinchilla Pokémon');
INSERT INTO especies (id,name) VALUES (424, 'Scarf Pokémon');
INSERT INTO especies (id,name) VALUES (425, 'Fixation Pokémon');
INSERT INTO especies (id,name) VALUES (426, 'Astral Body Pokémon');
INSERT INTO especies (id,name) VALUES (427, 'Cell Pokémon');
INSERT INTO especies (id,name) VALUES (428, 'Mitosis Pokémon');
INSERT INTO especies (id,name) VALUES (429, 'Multiplying Pokémon');
INSERT INTO especies (id,name) VALUES (430, 'White Bird Pokémon');
INSERT INTO especies (id,name) VALUES (431, 'Icy Snow Pokémon');
INSERT INTO especies (id,name) VALUES (432, 'Snowstorm Pokémon');
INSERT INTO especies (id,name) VALUES (433, 'Season Pokémon');
INSERT INTO especies (id,name) VALUES (434, 'Sky Squirrel Pokémon');
INSERT INTO especies (id,name) VALUES (435, 'Clamping Pokémon');
INSERT INTO especies (id,name) VALUES (436, 'Cavalry Pokémon');
INSERT INTO especies (id,name) VALUES (437, 'Floating Pokémon');
INSERT INTO especies (id,name) VALUES (438, 'Caring Pokémon');
INSERT INTO especies (id,name) VALUES (439, 'Attaching Pokémon');
INSERT INTO especies (id,name) VALUES (440, 'EleSpider Pokémon');
INSERT INTO especies (id,name) VALUES (441, 'Thorn Seed Pokémon');
INSERT INTO especies (id,name) VALUES (442, 'Thorn Pod Pokémon');
INSERT INTO especies (id,name) VALUES (443, 'Gear Pokémon');
INSERT INTO especies (id,name) VALUES (444, 'EleFish Pokémon');
INSERT INTO especies (id,name) VALUES (445, 'Cerebral Pokémon');
INSERT INTO especies (id,name) VALUES (446, 'Candle Pokémon');
INSERT INTO especies (id,name) VALUES (447, 'Lamp Pokémon');
INSERT INTO especies (id,name) VALUES (448, 'Luring Pokémon');
INSERT INTO especies (id,name) VALUES (449, 'Tusk Pokémon');
INSERT INTO especies (id,name) VALUES (450, 'Axe Jaw Pokémon');
INSERT INTO especies (id,name) VALUES (451, 'Chill Pokémon');
INSERT INTO especies (id,name) VALUES (452, 'Freezing Pokémon');
INSERT INTO especies (id,name) VALUES (453, 'Crystallizing Pokémon');
INSERT INTO especies (id,name) VALUES (454, 'Snail Pokémon');
INSERT INTO especies (id,name) VALUES (455, 'Shell Out Pokémon');
INSERT INTO especies (id,name) VALUES (456, 'Trap Pokémon');
INSERT INTO especies (id,name) VALUES (457, 'Martial Arts Pokémon');
INSERT INTO especies (id,name) VALUES (458, 'Automaton Pokémon');
INSERT INTO especies (id,name) VALUES (459, 'Sharp Blade Pokémon');
INSERT INTO especies (id,name) VALUES (460, 'Sword Blade Pokémon');
INSERT INTO especies (id,name) VALUES (461, 'Bash Buffalo Pokémon');
INSERT INTO especies (id,name) VALUES (462, 'Eaglet Pokémon');
INSERT INTO especies (id,name) VALUES (463, 'Valiant Pokémon');
INSERT INTO especies (id,name) VALUES (464, 'Diapered Pokémon');
INSERT INTO especies (id,name) VALUES (465, 'Bone Vulture Pokémon');
INSERT INTO especies (id,name) VALUES (466, 'Anteater Pokémon');
INSERT INTO especies (id,name) VALUES (467, 'Iron Ant Pokémon');
INSERT INTO especies (id,name) VALUES (468, 'Irate Pokémon');
INSERT INTO especies (id,name) VALUES (469, 'Torch Pokémon');
INSERT INTO especies (id,name) VALUES (470, 'Iron Will Pokémon');
INSERT INTO especies (id,name) VALUES (471, 'Cavern Pokémon');
INSERT INTO especies (id,name) VALUES (472, 'Grassland Pokémon');
INSERT INTO especies (id,name) VALUES (473, 'Cyclone Pokémon');
INSERT INTO especies (id,name) VALUES (474, 'Bolt Strike Pokémon');
INSERT INTO especies (id,name) VALUES (475, 'Vast White Pokémon');
INSERT INTO especies (id,name) VALUES (476, 'Deep Black Pokémon');
INSERT INTO especies (id,name) VALUES (477, 'Abundance Pokémon');
INSERT INTO especies (id,name) VALUES (478, 'Boundary Pokémon');
INSERT INTO especies (id,name) VALUES (479, 'Colt Pokémon');
INSERT INTO especies (id,name) VALUES (480, 'Melody Pokémon');
INSERT INTO especies (id,name) VALUES (481, 'Paleozoic Pokémon');
INSERT INTO especies (id,name) VALUES (482, 'Spiny Nut Pokémon');
INSERT INTO especies (id,name) VALUES (483, 'Spiny Armor Pokémon');
INSERT INTO especies (id,name) VALUES (484, 'Bubble Frog Pokémon');
INSERT INTO especies (id,name) VALUES (485, 'Digging Pokémon');
INSERT INTO especies (id,name) VALUES (486, 'Tiny Robin Pokémon');
INSERT INTO especies (id,name) VALUES (487, 'Scorching Pokémon');
INSERT INTO especies (id,name) VALUES (488, 'Scatterdust Pokémon');
INSERT INTO especies (id,name) VALUES (489, 'Scale Pokémon');
INSERT INTO especies (id,name) VALUES (490, 'Lion Cub Pokémon');
INSERT INTO especies (id,name) VALUES (491, 'Single Bloom Pokémon');
INSERT INTO especies (id,name) VALUES (492, 'Garden Pokémon');
INSERT INTO especies (id,name) VALUES (493, 'Mount Pokémon');
INSERT INTO especies (id,name) VALUES (494, 'Daunting Pokémon');
INSERT INTO especies (id,name) VALUES (495, 'Poodle Pokémon');
INSERT INTO especies (id,name) VALUES (496, 'Restraint Pokémon');
INSERT INTO especies (id,name) VALUES (497, 'Constraint Pokémon');
INSERT INTO especies (id,name) VALUES (498, 'Sword Pokémon');
INSERT INTO especies (id,name) VALUES (499, 'Royal Sword Pokémon');
INSERT INTO especies (id,name) VALUES (500, 'Perfume Pokémon');
INSERT INTO especies (id,name) VALUES (501, 'Fragrance Pokémon');
INSERT INTO especies (id,name) VALUES (502, 'Cotton Candy Pokémon');
INSERT INTO especies (id,name) VALUES (503, 'Meringue Pokémon');
INSERT INTO especies (id,name) VALUES (504, 'Revolving Pokémon');
INSERT INTO especies (id,name) VALUES (505, 'Overturning Pokémon');
INSERT INTO especies (id,name) VALUES (506, 'Two-Handed Pokémon');
INSERT INTO especies (id,name) VALUES (507, 'Collective Pokémon');
INSERT INTO especies (id,name) VALUES (508, 'Mock Kelp Pokémon');
INSERT INTO especies (id,name) VALUES (509, 'Water Gun Pokémon');
INSERT INTO especies (id,name) VALUES (510, 'Howitzer Pokémon');
INSERT INTO especies (id,name) VALUES (511, 'Generator Pokémon');
INSERT INTO especies (id,name) VALUES (512, 'Royal Heir Pokémon');
INSERT INTO especies (id,name) VALUES (513, 'Despot Pokémon');
INSERT INTO especies (id,name) VALUES (514, 'Tundra Pokémon');
INSERT INTO especies (id,name) VALUES (515, 'Intertwining Pokémon');
INSERT INTO especies (id,name) VALUES (516, 'Wrestling Pokémon');
INSERT INTO especies (id,name) VALUES (517, 'Antenna Pokémon');
INSERT INTO especies (id,name) VALUES (518, 'Jewel Pokémon');
INSERT INTO especies (id,name) VALUES (519, 'Soft Tissue Pokémon');
INSERT INTO especies (id,name) VALUES (520, 'Key Ring Pokémon');
INSERT INTO especies (id,name) VALUES (521, 'Stump Pokémon');
INSERT INTO especies (id,name) VALUES (522, 'Elder Tree Pokémon');
INSERT INTO especies (id,name) VALUES (523, 'Pumpkin Pokémon');
INSERT INTO especies (id,name) VALUES (524, 'Ice Chunk Pokémon');
INSERT INTO especies (id,name) VALUES (525, 'Sound Wave Pokémon');
INSERT INTO especies (id,name) VALUES (526, 'Life Pokémon');
INSERT INTO especies (id,name) VALUES (527, 'Destruction Pokémon');
INSERT INTO especies (id,name) VALUES (528, 'Order Pokémon');
INSERT INTO especies (id,name) VALUES (529, 'Mischief Pokémon');
INSERT INTO especies (id,name) VALUES (530, 'Djinn Pokémon');
INSERT INTO especies (id,name) VALUES (531, 'Steam Pokémon');
INSERT INTO especies (id,name) VALUES (532, 'Grass Quill Pokémon');
INSERT INTO especies (id,name) VALUES (533, 'Blade Quill Pokémon');
INSERT INTO especies (id,name) VALUES (534, 'Arrow Quill Pokémon');
INSERT INTO especies (id,name) VALUES (535, 'Fire Cat Pokémon');
INSERT INTO especies (id,name) VALUES (536, 'Heel Pokémon');
INSERT INTO especies (id,name) VALUES (537, 'Pop Star Pokémon');
INSERT INTO especies (id,name) VALUES (538, 'Soloist Pokémon');
INSERT INTO especies (id,name) VALUES (539, 'Woodpecker Pokémon');
INSERT INTO especies (id,name) VALUES (540, 'Bugle Beak Pokémon');
INSERT INTO especies (id,name) VALUES (541, 'Cannon Pokémon');
INSERT INTO especies (id,name) VALUES (542, 'Loitering Pokémon');
INSERT INTO especies (id,name) VALUES (543, 'Stakeout Pokémon');
INSERT INTO especies (id,name) VALUES (544, 'Larva Pokémon');
INSERT INTO especies (id,name) VALUES (545, 'Battery Pokémon');
INSERT INTO especies (id,name) VALUES (546, 'Boxing Pokémon');
INSERT INTO especies (id,name) VALUES (547, 'Woolly Crab Pokémon');
INSERT INTO especies (id,name) VALUES (548, 'Bee Fly Pokémon');
INSERT INTO especies (id,name) VALUES (549, 'Wolf Pokémon');
INSERT INTO especies (id,name) VALUES (550, 'Small Fry Pokémon');
INSERT INTO especies (id,name) VALUES (551, 'Brutal Star Pokémon');
INSERT INTO especies (id,name) VALUES (552, 'Donkey Pokémon');
INSERT INTO especies (id,name) VALUES (553, 'Draft Horse Pokémon');
INSERT INTO especies (id,name) VALUES (554, 'Water Bubble Pokémon');
INSERT INTO especies (id,name) VALUES (555, 'Sickle Grass Pokémon');
INSERT INTO especies (id,name) VALUES (556, 'Bloom Sickle Pokémon');
INSERT INTO especies (id,name) VALUES (557, 'Illuminating Pokémon');
INSERT INTO especies (id,name) VALUES (558, 'Toxic Lizard Pokémon');
INSERT INTO especies (id,name) VALUES (559, 'Flailing Pokémon');
INSERT INTO especies (id,name) VALUES (560, 'Strong Arm Pokémon');
INSERT INTO especies (id,name) VALUES (561, 'Posy Picker Pokémon');
INSERT INTO especies (id,name) VALUES (562, 'Sage Pokémon');
INSERT INTO especies (id,name) VALUES (563, 'Teamwork Pokémon');
INSERT INTO especies (id,name) VALUES (564, 'Turn Tail Pokémon');
INSERT INTO especies (id,name) VALUES (565, 'Hard Scale Pokémon');
INSERT INTO especies (id,name) VALUES (566, 'Sand Heap Pokémon');
INSERT INTO especies (id,name) VALUES (567, 'Sand Castle Pokémon');
INSERT INTO especies (id,name) VALUES (568, 'Sea Cucumber Pokémon');
INSERT INTO especies (id,name) VALUES (569, 'Synthetic Pokémon');
INSERT INTO especies (id,name) VALUES (570, 'Meteor Pokémon');
INSERT INTO especies (id,name) VALUES (571, 'Blast Turtle Pokémon');
INSERT INTO especies (id,name) VALUES (572, 'Roly-Poly Pokémon');
INSERT INTO especies (id,name) VALUES (573, 'Disguise Pokémon');
INSERT INTO especies (id,name) VALUES (574, 'Gnash Teeth Pokémon');
INSERT INTO especies (id,name) VALUES (575, 'Placid Pokémon');
INSERT INTO especies (id,name) VALUES (576, 'Sea Creeper Pokémon');
INSERT INTO especies (id,name) VALUES (577, 'Scaly Pokémon');
INSERT INTO especies (id,name) VALUES (578, 'Land Spirit Pokémon');
INSERT INTO especies (id,name) VALUES (579, 'Nebula Pokémon');
INSERT INTO especies (id,name) VALUES (580, 'Protostar Pokémon');
INSERT INTO especies (id,name) VALUES (581, 'Sunne Pokémon');
INSERT INTO especies (id,name) VALUES (582, 'Moone Pokémon');
INSERT INTO especies (id,name) VALUES (583, 'Parasite Pokémon');
INSERT INTO especies (id,name) VALUES (584, 'Swollen Pokémon');
INSERT INTO especies (id,name) VALUES (585, 'Lissome Pokémon');
INSERT INTO especies (id,name) VALUES (586, 'Glowing Pokémon');
INSERT INTO especies (id,name) VALUES (587, 'Launch Pokémon');
INSERT INTO especies (id,name) VALUES (588, 'Drawn Sword Pokémon');
INSERT INTO especies (id,name) VALUES (589, 'Junkivore Pokémon');
INSERT INTO especies (id,name) VALUES (590, 'Prism Pokémon');
INSERT INTO especies (id,name) VALUES (591, 'Artificial Pokémon');
INSERT INTO especies (id,name) VALUES (592, 'Gloomdweller Pokémon');
INSERT INTO especies (id,name) VALUES (593, 'Rampart Pokémon');
INSERT INTO especies (id,name) VALUES (594, 'Fireworks Pokémon');
INSERT INTO especies (id,name) VALUES (595, 'Thunderclap Pokémon');
INSERT INTO especies (id,name) VALUES (596, 'Hex Nut Pokémon');
INSERT INTO especies (id,name) VALUES (597, 'Beat Pokémon');
INSERT INTO especies (id,name) VALUES (598, 'Drummer Pokémon');
INSERT INTO especies (id,name) VALUES (599, 'Striker Pokémon');
INSERT INTO especies (id,name) VALUES (600, 'Water Lizard Pokémon');
INSERT INTO especies (id,name) VALUES (601, 'Water lizard Pokémon');
INSERT INTO especies (id,name) VALUES (602, 'Secret Agent Pokémon');
INSERT INTO especies (id,name) VALUES (603, 'Cheeky Pokémon');
INSERT INTO especies (id,name) VALUES (604, 'Greedy Pokémon');
INSERT INTO especies (id,name) VALUES (605, 'Raven Pokémon');
INSERT INTO especies (id,name) VALUES (606, 'Radome Pokémon');
INSERT INTO especies (id,name) VALUES (607, 'Seven Spot Pokémon');
INSERT INTO especies (id,name) VALUES (608, 'Cotton Bloom Pokémon');
INSERT INTO especies (id,name) VALUES (609, 'Sheep Pokémon');
INSERT INTO especies (id,name) VALUES (610, 'Snapping Pokémon');
INSERT INTO especies (id,name) VALUES (611, 'Dog Pokémon');
INSERT INTO especies (id,name) VALUES (612, 'Apple Core Pokémon');
INSERT INTO especies (id,name) VALUES (613, 'Apple Wing Pokémon');
INSERT INTO especies (id,name) VALUES (614, 'Apple Nectar Pokémon');
INSERT INTO especies (id,name) VALUES (615, 'Sand Snake Pokémon');
INSERT INTO especies (id,name) VALUES (616, 'Gulp Pokémon');
INSERT INTO especies (id,name) VALUES (617, 'Rush Pokémon');
INSERT INTO especies (id,name) VALUES (618, 'Skewer Pokémon');
INSERT INTO especies (id,name) VALUES (619, 'Baby Pokémon');
INSERT INTO especies (id,name) VALUES (620, 'Punk Pokémon');
INSERT INTO especies (id,name) VALUES (621, 'Radiator Pokémon');
INSERT INTO especies (id,name) VALUES (622, 'Tantrum Pokémon');
INSERT INTO especies (id,name) VALUES (623, 'Black Tea Pokémon');
INSERT INTO especies (id,name) VALUES (624, 'Calm Pokémon');
INSERT INTO especies (id,name) VALUES (625, 'Serene Pokémon');
INSERT INTO especies (id,name) VALUES (626, 'Silent Pokémon');
INSERT INTO especies (id,name) VALUES (627, 'Bulk Up Pokémon');
INSERT INTO especies (id,name) VALUES (628, 'Blocking Pokémon');
INSERT INTO especies (id,name) VALUES (629, 'Viking Pokémon');
INSERT INTO especies (id,name) VALUES (630, 'Comedian Pokémon');
INSERT INTO especies (id,name) VALUES (631, 'Grudge Pokémon');
INSERT INTO especies (id,name) VALUES (632, 'Cream Pokémon');
INSERT INTO especies (id,name) VALUES (633, 'Formation Pokémon');
INSERT INTO especies (id,name) VALUES (634, 'Sea Urchin Pokémon');
INSERT INTO especies (id,name) VALUES (635, 'Frost Moth Pokémon');
INSERT INTO especies (id,name) VALUES (636, 'Big Rock Pokémon');
INSERT INTO especies (id,name) VALUES (637, 'Two-Sided Pokémon');
INSERT INTO especies (id,name) VALUES (638, 'Copperderm Pokémon');
INSERT INTO especies (id,name) VALUES (639, 'Alloy Pokémon');
INSERT INTO especies (id,name) VALUES (640, 'Lingering Pokémon');
INSERT INTO especies (id,name) VALUES (641, 'Caretaker Pokémon');
INSERT INTO especies (id,name) VALUES (642, 'Stealth Pokémon');
INSERT INTO especies (id,name) VALUES (643, 'Warrior Pokémon');
INSERT INTO especies (id,name) VALUES (644, 'Gigantic Pokémon');
INSERT INTO especies (id,name) VALUES (645, 'Wushu Pokémon');
INSERT INTO especies (id,name) VALUES (646, 'Rogue Monkey Pokémon');
INSERT INTO especies (id,name) VALUES (647, 'Elektron Pokémon');
INSERT INTO especies (id,name) VALUES (648, 'Dragon Orb Pokémon');
INSERT INTO especies (id,name) VALUES (649, 'Wild Horse Pokémon');
INSERT INTO especies (id,name) VALUES (650, 'Swift Horse Pokémon');
INSERT INTO especies (id,name) VALUES (651, 'King Pokémon');
INSERT INTO especies (id,name) VALUES (652, 'High King Pokémon');

-- migration:down 

 DELETE FROM especies;