-- migration: up 


INSERT INTO habilidades (id, nombre) VALUES (1, 'Analytic');
INSERT INTO habilidades (id, nombre) VALUES (2, 'Anticipation');
INSERT INTO habilidades (id, nombre) VALUES (3, 'Cloud Nine');
INSERT INTO habilidades (id, nombre) VALUES (4, 'Cursed Body');
INSERT INTO habilidades (id, nombre) VALUES (5, 'Cute Charm');
INSERT INTO habilidades (id, nombre) VALUES (6, 'Damp');
INSERT INTO habilidades (id, nombre) VALUES (7, 'Defiant');
INSERT INTO habilidades (id, nombre) VALUES (8, 'Download');
INSERT INTO habilidades (id, nombre) VALUES (9, 'Drizzle');
INSERT INTO habilidades (id, nombre) VALUES (10, 'Dry Skin');
INSERT INTO habilidades (id, nombre) VALUES (11, 'Early Bird');
INSERT INTO habilidades (id, nombre) VALUES (12, 'Effect Spore');
INSERT INTO habilidades (id, nombre) VALUES (13, 'Flare Boost');
INSERT INTO habilidades (id, nombre) VALUES (14, 'Flash Fire');
INSERT INTO habilidades (id, nombre) VALUES (15, 'Fluffy');
INSERT INTO habilidades (id, nombre) VALUES (16, 'Forewarn');
INSERT INTO habilidades (id, nombre) VALUES (17, 'Friend Guard');
INSERT INTO habilidades (id, nombre) VALUES (18, 'Frisk');
INSERT INTO habilidades (id, nombre) VALUES (19, 'Gale Wings');
INSERT INTO habilidades (id, nombre) VALUES (20, 'Gluttony');
INSERT INTO habilidades (id, nombre) VALUES (21, 'Guts');
INSERT INTO habilidades (id, nombre) VALUES (22, 'Harvest');
INSERT INTO habilidades (id, nombre) VALUES (23, 'Healer');
INSERT INTO habilidades (id, nombre) VALUES (24, 'Heatproof');
INSERT INTO habilidades (id, nombre) VALUES (25, 'Heavy Metal');
INSERT INTO habilidades (id, nombre) VALUES (26, 'Huge Power');
INSERT INTO habilidades (id, nombre) VALUES (27, 'Hustle');
INSERT INTO habilidades (id, nombre) VALUES (28, 'Hydration');
INSERT INTO habilidades (id, nombre) VALUES (29, 'Hyper Cutter');
INSERT INTO habilidades (id, nombre) VALUES (30, 'Ice Body');
INSERT INTO habilidades (id, nombre) VALUES (31, 'Illuminate');
INSERT INTO habilidades (id, nombre) VALUES (32, 'Immunity');
INSERT INTO habilidades (id, nombre) VALUES (33, 'Infiltrator');
INSERT INTO habilidades (id, nombre) VALUES (34, 'Inner Focus');
INSERT INTO habilidades (id, nombre) VALUES (35, 'Insomnia');
INSERT INTO habilidades (id, nombre) VALUES (36, 'Intimidate');
INSERT INTO habilidades (id, nombre) VALUES (37, 'Iron Barbs');
INSERT INTO habilidades (id, nombre) VALUES (38, 'Iron Fist');
INSERT INTO habilidades (id, nombre) VALUES (39, 'Justified');
INSERT INTO habilidades (id, nombre) VALUES (40, 'Keen Eye');
INSERT INTO habilidades (id, nombre) VALUES (41, 'Klutz');
INSERT INTO habilidades (id, nombre) VALUES (42, 'Leaf Guard');
INSERT INTO habilidades (id, nombre) VALUES (43, 'Levitate');
INSERT INTO habilidades (id, nombre) VALUES (44, 'Libero');
INSERT INTO habilidades (id, nombre) VALUES (45, 'Light Metal');
INSERT INTO habilidades (id, nombre) VALUES (46, 'Lightning Rod');
INSERT INTO habilidades (id, nombre) VALUES (47, 'Limber');
INSERT INTO habilidades (id, nombre) VALUES (48, 'Liquid Ooze');
INSERT INTO habilidades (id, nombre) VALUES (49, 'Magic Bounce');
INSERT INTO habilidades (id, nombre) VALUES (50, 'Magic Guard');
INSERT INTO habilidades (id, nombre) VALUES (51, 'Magician');
INSERT INTO habilidades (id, nombre) VALUES (52, 'Magma Armor');
INSERT INTO habilidades (id, nombre) VALUES (53, 'Magnet Pull');
INSERT INTO habilidades (id, nombre) VALUES (54, 'Marvel Scale');
INSERT INTO habilidades (id, nombre) VALUES (55, 'Merciless');
INSERT INTO habilidades (id, nombre) VALUES (56, 'Minus');
INSERT INTO habilidades (id, nombre) VALUES (57, 'Misty Surge');
INSERT INTO habilidades (id, nombre) VALUES (58, 'Mold Breaker');
INSERT INTO habilidades (id, nombre) VALUES (59, 'Moody');
INSERT INTO habilidades (id, nombre) VALUES (60, 'Motor Drive');
INSERT INTO habilidades (id, nombre) VALUES (61, 'Moxie');
INSERT INTO habilidades (id, nombre) VALUES (62, 'Multiscale');
INSERT INTO habilidades (id, nombre) VALUES (63, 'Natural Cure');
INSERT INTO habilidades (id, nombre) VALUES (64, 'Neutralizing Gas');
INSERT INTO habilidades (id, nombre) VALUES (65, 'No Guard');
INSERT INTO habilidades (id, nombre) VALUES (66, 'Normalize');
INSERT INTO habilidades (id, nombre) VALUES (67, 'Oblivious');
INSERT INTO habilidades (id, nombre) VALUES (68, 'Overcoat');
INSERT INTO habilidades (id, nombre) VALUES (69, 'Overgrow');
INSERT INTO habilidades (id, nombre) VALUES (70, 'Own Tempo');
INSERT INTO habilidades (id, nombre) VALUES (71, 'Pastel Veil');
INSERT INTO habilidades (id, nombre) VALUES (72, 'Pickpocket');
INSERT INTO habilidades (id, nombre) VALUES (73, 'Pickup');
INSERT INTO habilidades (id, nombre) VALUES (74, 'Pixilate');
INSERT INTO habilidades (id, nombre) VALUES (75, 'Plus');
INSERT INTO habilidades (id, nombre) VALUES (76, 'Poison Heal');
INSERT INTO habilidades (id, nombre) VALUES (77, 'Poison Point');
INSERT INTO habilidades (id, nombre) VALUES (78, 'Poison Touch');
INSERT INTO habilidades (id, nombre) VALUES (79, 'Power Construct');
INSERT INTO habilidades (id, nombre) VALUES (80, 'Power of Alchemy');
INSERT INTO habilidades (id, nombre) VALUES (81, 'Prankster');
INSERT INTO habilidades (id, nombre) VALUES (82, 'Pressure');
INSERT INTO habilidades (id, nombre) VALUES (83, 'Protean');
INSERT INTO habilidades (id, nombre) VALUES (84, 'Psychic Surge');
INSERT INTO habilidades (id, nombre) VALUES (85, 'Punk Rock');
INSERT INTO habilidades (id, nombre) VALUES (86, 'Queenly Majesty');
INSERT INTO habilidades (id, nombre) VALUES (87, 'Quick Draw');
INSERT INTO habilidades (id, nombre) VALUES (88, 'Quick Feet');
INSERT INTO habilidades (id, nombre) VALUES (89, 'Rain Dish');
INSERT INTO habilidades (id, nombre) VALUES (90, 'Rattled');
INSERT INTO habilidades (id, nombre) VALUES (91, 'Receiver');
INSERT INTO habilidades (id, nombre) VALUES (92, 'Reckless');
INSERT INTO habilidades (id, nombre) VALUES (93, 'Regenerator');
INSERT INTO habilidades (id, nombre) VALUES (94, 'Ripen');
INSERT INTO habilidades (id, nombre) VALUES (95, 'Rivalry');
INSERT INTO habilidades (id, nombre) VALUES (96, 'Rock Head');
INSERT INTO habilidades (id, nombre) VALUES (97, 'Rough Skin');
INSERT INTO habilidades (id, nombre) VALUES (98, 'Run Away');
INSERT INTO habilidades (id, nombre) VALUES (99, 'Sand Force');
INSERT INTO habilidades (id, nombre) VALUES (100, 'Sand Rush');
INSERT INTO habilidades (id, nombre) VALUES (101, 'Sand Stream');
INSERT INTO habilidades (id, nombre) VALUES (102, 'Sand Veil');
INSERT INTO habilidades (id, nombre) VALUES (103, 'Sap Sipper');
INSERT INTO habilidades (id, nombre) VALUES (104, 'Scrappy');
INSERT INTO habilidades (id, nombre) VALUES (105, 'Screen Cleaner');
INSERT INTO habilidades (id, nombre) VALUES (106, 'Serene Grace');
INSERT INTO habilidades (id, nombre) VALUES (107, 'Shadow Tag');
INSERT INTO habilidades (id, nombre) VALUES (108, 'Shed Skin');
INSERT INTO habilidades (id, nombre) VALUES (109, 'Sheer Force');
INSERT INTO habilidades (id, nombre) VALUES (110, 'Shell Armor');
INSERT INTO habilidades (id, nombre) VALUES (111, 'Shield Dust');
INSERT INTO habilidades (id, nombre) VALUES (112, 'Simple');
INSERT INTO habilidades (id, nombre) VALUES (113, 'Skill Link');
INSERT INTO habilidades (id, nombre) VALUES (114, 'Slush Rush');
INSERT INTO habilidades (id, nombre) VALUES (115, 'Sniper');
INSERT INTO habilidades (id, nombre) VALUES (116, 'Snow Cloak');
INSERT INTO habilidades (id, nombre) VALUES (117, 'Snow Warning');
INSERT INTO habilidades (id, nombre) VALUES (118, 'Solar Power');
INSERT INTO habilidades (id, nombre) VALUES (119, 'Solid Rock');
INSERT INTO habilidades (id, nombre) VALUES (120, 'Soundproof');
INSERT INTO habilidades (id, nombre) VALUES (121, 'Speed Boost');
INSERT INTO habilidades (id, nombre) VALUES (122, 'Stakeout');
INSERT INTO habilidades (id, nombre) VALUES (123, 'Stall');
INSERT INTO habilidades (id, nombre) VALUES (124, 'Stalwart');
INSERT INTO habilidades (id, nombre) VALUES (125, 'Stamina');
INSERT INTO habilidades (id, nombre) VALUES (126, 'Static');
INSERT INTO habilidades (id, nombre) VALUES (127, 'Steadfast');
INSERT INTO habilidades (id, nombre) VALUES (128, 'Steam Engine');
INSERT INTO habilidades (id, nombre) VALUES (129, 'Steely Spirit');
INSERT INTO habilidades (id, nombre) VALUES (130, 'Stench');
INSERT INTO habilidades (id, nombre) VALUES (131, 'Sticky Hold');
INSERT INTO habilidades (id, nombre) VALUES (132, 'Storm Drain');
INSERT INTO habilidades (id, nombre) VALUES (133, 'Strong Jaw');
INSERT INTO habilidades (id, nombre) VALUES (134, 'Sturdy');
INSERT INTO habilidades (id, nombre) VALUES (135, 'Suction Cups');
INSERT INTO habilidades (id, nombre) VALUES (136, 'Super Luck');
INSERT INTO habilidades (id, nombre) VALUES (137, 'Swarm');
INSERT INTO habilidades (id, nombre) VALUES (138, 'Sweet Veil');
INSERT INTO habilidades (id, nombre) VALUES (139, 'Swift Swim');
INSERT INTO habilidades (id, nombre) VALUES (140, 'Symbiosis');
INSERT INTO habilidades (id, nombre) VALUES (141, 'Synchronize');
INSERT INTO habilidades (id, nombre) VALUES (142, 'Tangled Feet');
INSERT INTO habilidades (id, nombre) VALUES (143, 'Tangling Hair');
INSERT INTO habilidades (id, nombre) VALUES (144, 'Technician');
INSERT INTO habilidades (id, nombre) VALUES (145, 'Telepathy');
INSERT INTO habilidades (id, nombre) VALUES (146, 'Thick Fat');
INSERT INTO habilidades (id, nombre) VALUES (147, 'Tinted Lens');
INSERT INTO habilidades (id, nombre) VALUES (148, 'Torrent');
INSERT INTO habilidades (id, nombre) VALUES (149, 'Tough Claws');
INSERT INTO habilidades (id, nombre) VALUES (150, 'Toxic Boost');
INSERT INTO habilidades (id, nombre) VALUES (151, 'Trace');
INSERT INTO habilidades (id, nombre) VALUES (152, 'Triage');
INSERT INTO habilidades (id, nombre) VALUES (153, 'Truant');
INSERT INTO habilidades (id, nombre) VALUES (154, 'Unaware');
INSERT INTO habilidades (id, nombre) VALUES (155, 'Unburden');
INSERT INTO habilidades (id, nombre) VALUES (156, 'Unnerve');
INSERT INTO habilidades (id, nombre) VALUES (157, 'Vital Spirit');
INSERT INTO habilidades (id, nombre) VALUES (158, 'Volt Absorb');
INSERT INTO habilidades (id, nombre) VALUES (159, 'Water Absorb');
INSERT INTO habilidades (id, nombre) VALUES (160, 'Water Bubble');
INSERT INTO habilidades (id, nombre) VALUES (161, 'Water Compaction');
INSERT INTO habilidades (id, nombre) VALUES (162, 'Water Veil');
INSERT INTO habilidades (id, nombre) VALUES (163, 'Weak Armor');
INSERT INTO habilidades (id, nombre) VALUES (164, 'White Smoke');
INSERT INTO habilidades (id, nombre) VALUES (165, 'Wonder Skin');
INSERT INTO habilidades (id, nombre) VALUES (166, 'Zen Mode');
INSERT INTO habilidades (id, nombre) VALUES (167, 'Adaptability');
INSERT INTO habilidades (id, nombre) VALUES (168, 'Aerilate');
INSERT INTO habilidades (id, nombre) VALUES (169, 'Aftermath');
INSERT INTO habilidades (id, nombre) VALUES (170, 'Air Lock');
INSERT INTO habilidades (id, nombre) VALUES (171, 'Analytic');
INSERT INTO habilidades (id, nombre) VALUES (172, 'Anger Point');
INSERT INTO habilidades (id, nombre) VALUES (173, 'Anticipation');
INSERT INTO habilidades (id, nombre) VALUES (174, 'Arena Trap');
INSERT INTO habilidades (id, nombre) VALUES (175, 'Aroma Veil');
INSERT INTO habilidades (id, nombre) VALUES (176, 'As One');
INSERT INTO habilidades (id, nombre) VALUES (177, 'Aura Break');
INSERT INTO habilidades (id, nombre) VALUES (178, 'Bad Dreams');
INSERT INTO habilidades (id, nombre) VALUES (179, 'Ball Fetch');
INSERT INTO habilidades (id, nombre) VALUES (180, 'Battery');
INSERT INTO habilidades (id, nombre) VALUES (181, 'Battle Armor');
INSERT INTO habilidades (id, nombre) VALUES (182, 'Battle Bond');
INSERT INTO habilidades (id, nombre) VALUES (183, 'Beast Boost');
INSERT INTO habilidades (id, nombre) VALUES (184, 'Berserk');
INSERT INTO habilidades (id, nombre) VALUES (185, 'Big Pecks');
INSERT INTO habilidades (id, nombre) VALUES (186, 'Blaze');
INSERT INTO habilidades (id, nombre) VALUES (187, 'Bulletproof');
INSERT INTO habilidades (id, nombre) VALUES (188, 'Cheek Pouch');
INSERT INTO habilidades (id, nombre) VALUES (189, 'Chilling Neigh');
INSERT INTO habilidades (id, nombre) VALUES (190, 'Chlorophyll');
INSERT INTO habilidades (id, nombre) VALUES (191, 'Clear Body');
INSERT INTO habilidades (id, nombre) VALUES (192, 'Cloud Nine');
INSERT INTO habilidades (id, nombre) VALUES (193, 'Color Change');
INSERT INTO habilidades (id, nombre) VALUES (194, 'Comatose');
INSERT INTO habilidades (id, nombre) VALUES (195, 'Competitive');
INSERT INTO habilidades (id, nombre) VALUES (196, 'Contrary');
INSERT INTO habilidades (id, nombre) VALUES (197, 'Corrosion');
INSERT INTO habilidades (id, nombre) VALUES (198, 'Cotton Down');
INSERT INTO habilidades (id, nombre) VALUES (199, 'Curious Medicine');
INSERT INTO habilidades (id, nombre) VALUES (200, 'Cursed Body');
INSERT INTO habilidades (id, nombre) VALUES (201, 'Cute Charm');
INSERT INTO habilidades (id, nombre) VALUES (202, 'Damp');
INSERT INTO habilidades (id, nombre) VALUES (203, 'Dancer');
INSERT INTO habilidades (id, nombre) VALUES (204, 'Dark Aura');
INSERT INTO habilidades (id, nombre) VALUES (205, 'Dauntless Shield');
INSERT INTO habilidades (id, nombre) VALUES (206, 'Dazzling');
INSERT INTO habilidades (id, nombre) VALUES (207, 'Defeatist');
INSERT INTO habilidades (id, nombre) VALUES (208, 'Defiant');
INSERT INTO habilidades (id, nombre) VALUES (209, 'Delta Stream');
INSERT INTO habilidades (id, nombre) VALUES (210, 'Desolate Land');
INSERT INTO habilidades (id, nombre) VALUES (211, 'Disguise');
INSERT INTO habilidades (id, nombre) VALUES (212, 'Download');
INSERT INTO habilidades (id, nombre) VALUES (213, 'Dragons Maw');
INSERT INTO habilidades (id, nombre) VALUES (214, 'Drizzle');
INSERT INTO habilidades (id, nombre) VALUES (215, 'Drought');
INSERT INTO habilidades (id, nombre) VALUES (216, 'Dry Skin');
INSERT INTO habilidades (id, nombre) VALUES (217, 'Early Bird');
INSERT INTO habilidades (id, nombre) VALUES (218, 'Effect Spore');
INSERT INTO habilidades (id, nombre) VALUES (219, 'Electric Surge');
INSERT INTO habilidades (id, nombre) VALUES (220, 'Emergency Exit');
INSERT INTO habilidades (id, nombre) VALUES (221, 'Fairy Aura');
INSERT INTO habilidades (id, nombre) VALUES (222, 'Filter');
INSERT INTO habilidades (id, nombre) VALUES (223, 'Flame Body');
INSERT INTO habilidades (id, nombre) VALUES (224, 'Flash Fire');
INSERT INTO habilidades (id, nombre) VALUES (225, 'Flower Gift');
INSERT INTO habilidades (id, nombre) VALUES (226, 'Flower Veil');
INSERT INTO habilidades (id, nombre) VALUES (227, 'Fluffy');
INSERT INTO habilidades (id, nombre) VALUES (228, 'Forecast');
INSERT INTO habilidades (id, nombre) VALUES (229, 'Forewarn');
INSERT INTO habilidades (id, nombre) VALUES (230, 'Friend Guard');
INSERT INTO habilidades (id, nombre) VALUES (231, 'Frisk');
INSERT INTO habilidades (id, nombre) VALUES (232, 'Full Metal Body');
INSERT INTO habilidades (id, nombre) VALUES (233, 'Fur Coat');
INSERT INTO habilidades (id, nombre) VALUES (234, 'Galvanize');
INSERT INTO habilidades (id, nombre) VALUES (235, 'Gluttony');
INSERT INTO habilidades (id, nombre) VALUES (236, 'Gooey');
INSERT INTO habilidades (id, nombre) VALUES (237, 'Gorilla Tactics');
INSERT INTO habilidades (id, nombre) VALUES (238, 'Grass Pelt');
INSERT INTO habilidades (id, nombre) VALUES (239, 'Grassy Surge');
INSERT INTO habilidades (id, nombre) VALUES (240, 'Grim Neigh');
INSERT INTO habilidades (id, nombre) VALUES (241, 'Gulp Missile');
INSERT INTO habilidades (id, nombre) VALUES (242, 'Guts');
INSERT INTO habilidades (id, nombre) VALUES (243, 'Healer');
INSERT INTO habilidades (id, nombre) VALUES (244, 'Heatproof');
INSERT INTO habilidades (id, nombre) VALUES (245, 'Heavy Metal');
INSERT INTO habilidades (id, nombre) VALUES (246, 'Honey Gather');
INSERT INTO habilidades (id, nombre) VALUES (247, 'Huge Power');
INSERT INTO habilidades (id, nombre) VALUES (248, 'Hunger Switch');
INSERT INTO habilidades (id, nombre) VALUES (249, 'Hustle');
INSERT INTO habilidades (id, nombre) VALUES (250, 'Hydration');
INSERT INTO habilidades (id, nombre) VALUES (251, 'Hyper Cutter');
INSERT INTO habilidades (id, nombre) VALUES (252, 'Ice Body');
INSERT INTO habilidades (id, nombre) VALUES (253, 'Ice Face');
INSERT INTO habilidades (id, nombre) VALUES (254, 'Ice Scales');
INSERT INTO habilidades (id, nombre) VALUES (255, 'Illuminate');
INSERT INTO habilidades (id, nombre) VALUES (256, 'Illusion');
INSERT INTO habilidades (id, nombre) VALUES (257, 'Immunity');
INSERT INTO habilidades (id, nombre) VALUES (258, 'Imposter');
INSERT INTO habilidades (id, nombre) VALUES (259, 'Infiltrator');
INSERT INTO habilidades (id, nombre) VALUES (260, 'Innards Out');
INSERT INTO habilidades (id, nombre) VALUES (261, 'Inner Focus');
INSERT INTO habilidades (id, nombre) VALUES (262, 'Insomnia');
INSERT INTO habilidades (id, nombre) VALUES (263, 'Intimidate');
INSERT INTO habilidades (id, nombre) VALUES (264, 'Intrepid Sword');
INSERT INTO habilidades (id, nombre) VALUES (265, 'Iron Barbs');
INSERT INTO habilidades (id, nombre) VALUES (266, 'Iron Fist');
INSERT INTO habilidades (id, nombre) VALUES (267, 'Justified');
INSERT INTO habilidades (id, nombre) VALUES (268, 'Keen Eye');
INSERT INTO habilidades (id, nombre) VALUES (269, 'Klutz');
INSERT INTO habilidades (id, nombre) VALUES (270, 'Leaf Guard');
INSERT INTO habilidades (id, nombre) VALUES (271, 'Levitate');
INSERT INTO habilidades (id, nombre) VALUES (272, 'Light Metal');
INSERT INTO habilidades (id, nombre) VALUES (273, 'Lightning Rod');
INSERT INTO habilidades (id, nombre) VALUES (274, 'Limber');
INSERT INTO habilidades (id, nombre) VALUES (275, 'Liquid Voice');
INSERT INTO habilidades (id, nombre) VALUES (276, 'Long Reach');
INSERT INTO habilidades (id, nombre) VALUES (277, 'Magic Bounce');
INSERT INTO habilidades (id, nombre) VALUES (278, 'Magic Guard');
INSERT INTO habilidades (id, nombre) VALUES (279, 'Magician');
INSERT INTO habilidades (id, nombre) VALUES (280, 'Magnet Pull');
INSERT INTO habilidades (id, nombre) VALUES (281, 'Marvel Scale');
INSERT INTO habilidades (id, nombre) VALUES (282, 'Mega Launcher');
INSERT INTO habilidades (id, nombre) VALUES (283, 'Mimicry');
INSERT INTO habilidades (id, nombre) VALUES (284, 'Minus');
INSERT INTO habilidades (id, nombre) VALUES (285, 'Mirror Armor');
INSERT INTO habilidades (id, nombre) VALUES (286, 'Misty Surge');
INSERT INTO habilidades (id, nombre) VALUES (287, 'Mold Breaker');
INSERT INTO habilidades (id, nombre) VALUES (288, 'Moody');
INSERT INTO habilidades (id, nombre) VALUES (289, 'Motor Drive');
INSERT INTO habilidades (id, nombre) VALUES (290, 'Moxie');
INSERT INTO habilidades (id, nombre) VALUES (291, 'Multiscale');
INSERT INTO habilidades (id, nombre) VALUES (292, 'Multitype');
INSERT INTO habilidades (id, nombre) VALUES (293, 'Mummy');
INSERT INTO habilidades (id, nombre) VALUES (294, 'Natural Cure');
INSERT INTO habilidades (id, nombre) VALUES (295, 'No Guard');
INSERT INTO habilidades (id, nombre) VALUES (296, 'Oblivious');
INSERT INTO habilidades (id, nombre) VALUES (297, 'Overcoat');
INSERT INTO habilidades (id, nombre) VALUES (298, 'Overgrow');
INSERT INTO habilidades (id, nombre) VALUES (299, 'Own Tempo');
INSERT INTO habilidades (id, nombre) VALUES (300, 'Parental Bond');
INSERT INTO habilidades (id, nombre) VALUES (301, 'Perish Body');
INSERT INTO habilidades (id, nombre) VALUES (302, 'Pickpocket');
INSERT INTO habilidades (id, nombre) VALUES (303, 'Pickup');
INSERT INTO habilidades (id, nombre) VALUES (304, 'Pixilate');
INSERT INTO habilidades (id, nombre) VALUES (305, 'Plus');
INSERT INTO habilidades (id, nombre) VALUES (306, 'Poison Point');
INSERT INTO habilidades (id, nombre) VALUES (307, 'Poison Touch');
INSERT INTO habilidades (id, nombre) VALUES (308, 'Power Spot');
INSERT INTO habilidades (id, nombre) VALUES (309, 'Prankster');
INSERT INTO habilidades (id, nombre) VALUES (310, 'Pressure');
INSERT INTO habilidades (id, nombre) VALUES (311, 'Primordial Sea');
INSERT INTO habilidades (id, nombre) VALUES (312, 'Prism Armor');
INSERT INTO habilidades (id, nombre) VALUES (313, 'Propeller Tail');
INSERT INTO habilidades (id, nombre) VALUES (314, 'Protean');
INSERT INTO habilidades (id, nombre) VALUES (315, 'Psychic Surge');
INSERT INTO habilidades (id, nombre) VALUES (316, 'Pure Power');
INSERT INTO habilidades (id, nombre) VALUES (317, 'Quick Feet');
INSERT INTO habilidades (id, nombre) VALUES (318, 'RKS System');
INSERT INTO habilidades (id, nombre) VALUES (319, 'Rain Dish');
INSERT INTO habilidades (id, nombre) VALUES (320, 'Rattled');
INSERT INTO habilidades (id, nombre) VALUES (321, 'Reckless');
INSERT INTO habilidades (id, nombre) VALUES (322, 'Refrigerate');
INSERT INTO habilidades (id, nombre) VALUES (323, 'Regenerator');
INSERT INTO habilidades (id, nombre) VALUES (324, 'Rivalry');
INSERT INTO habilidades (id, nombre) VALUES (325, 'Rock Head');
INSERT INTO habilidades (id, nombre) VALUES (326, 'Rough Skin');
INSERT INTO habilidades (id, nombre) VALUES (327, 'Run Away');
INSERT INTO habilidades (id, nombre) VALUES (328, 'Sand Force');
INSERT INTO habilidades (id, nombre) VALUES (329, 'Sand Rush');
INSERT INTO habilidades (id, nombre) VALUES (330, 'Sand Spit');
INSERT INTO habilidades (id, nombre) VALUES (331, 'Sand Stream');
INSERT INTO habilidades (id, nombre) VALUES (332, 'Sand Veil');
INSERT INTO habilidades (id, nombre) VALUES (333, 'Sap Sipper');
INSERT INTO habilidades (id, nombre) VALUES (334, 'Schooling');
INSERT INTO habilidades (id, nombre) VALUES (335, 'Scrappy');
INSERT INTO habilidades (id, nombre) VALUES (336, 'Serene Grace');
INSERT INTO habilidades (id, nombre) VALUES (337, 'Shadow Shield');
INSERT INTO habilidades (id, nombre) VALUES (338, 'Shadow Tag');
INSERT INTO habilidades (id, nombre) VALUES (339, 'Shed Skin');
INSERT INTO habilidades (id, nombre) VALUES (340, 'Sheer Force');
INSERT INTO habilidades (id, nombre) VALUES (341, 'Shell Armor');
INSERT INTO habilidades (id, nombre) VALUES (342, 'Shield Dust');
INSERT INTO habilidades (id, nombre) VALUES (343, 'Shields Down');
INSERT INTO habilidades (id, nombre) VALUES (344, 'Skill Link');
INSERT INTO habilidades (id, nombre) VALUES (345, 'Slow Start');
INSERT INTO habilidades (id, nombre) VALUES (346, 'Slush Rush');
INSERT INTO habilidades (id, nombre) VALUES (347, 'Sniper');
INSERT INTO habilidades (id, nombre) VALUES (348, 'Snow Cloak');
INSERT INTO habilidades (id, nombre) VALUES (349, 'Snow Warning');
INSERT INTO habilidades (id, nombre) VALUES (350, 'Solar Power');
INSERT INTO habilidades (id, nombre) VALUES (351, 'Solid Rock');
INSERT INTO habilidades (id, nombre) VALUES (352, 'Soul-Heart');
INSERT INTO habilidades (id, nombre) VALUES (353, 'Soundproof');
INSERT INTO habilidades (id, nombre) VALUES (354, 'Speed Boost');
INSERT INTO habilidades (id, nombre) VALUES (355, 'Stance Change');
INSERT INTO habilidades (id, nombre) VALUES (356, 'Static');
INSERT INTO habilidades (id, nombre) VALUES (357, 'Steadfast');
INSERT INTO habilidades (id, nombre) VALUES (358, 'Steelworker');
INSERT INTO habilidades (id, nombre) VALUES (359, 'Storm Drain');
INSERT INTO habilidades (id, nombre) VALUES (360, 'Strong Jaw');
INSERT INTO habilidades (id, nombre) VALUES (361, 'Sturdy');
INSERT INTO habilidades (id, nombre) VALUES (362, 'Surge Surfer');
INSERT INTO habilidades (id, nombre) VALUES (363, 'Swarm');
INSERT INTO habilidades (id, nombre) VALUES (364, 'Sweet Veil');
INSERT INTO habilidades (id, nombre) VALUES (365, 'Swift Swim');
INSERT INTO habilidades (id, nombre) VALUES (366, 'Synchronize');
INSERT INTO habilidades (id, nombre) VALUES (367, 'Technician');
INSERT INTO habilidades (id, nombre) VALUES (368, 'Teravolt');
INSERT INTO habilidades (id, nombre) VALUES (369, 'Thick Fat');
INSERT INTO habilidades (id, nombre) VALUES (370, 'Tinted Lens');
INSERT INTO habilidades (id, nombre) VALUES (371, 'Tough Claws');
INSERT INTO habilidades (id, nombre) VALUES (372, 'Trace');
INSERT INTO habilidades (id, nombre) VALUES (373, 'Transistor');
INSERT INTO habilidades (id, nombre) VALUES (374, 'Truant');
INSERT INTO habilidades (id, nombre) VALUES (375, 'Turboblaze');
INSERT INTO habilidades (id, nombre) VALUES (376, 'Unaware');
INSERT INTO habilidades (id, nombre) VALUES (377, 'Unnerve');
INSERT INTO habilidades (id, nombre) VALUES (378, 'Unseen Fist');
INSERT INTO habilidades (id, nombre) VALUES (379, 'Victory Star');
INSERT INTO habilidades (id, nombre) VALUES (380, 'Vital Spirit');
INSERT INTO habilidades (id, nombre) VALUES (381, 'Volt Absorb');
INSERT INTO habilidades (id, nombre) VALUES (382, 'Wandering Spirit');
INSERT INTO habilidades (id, nombre) VALUES (383, 'Water Absorb');
INSERT INTO habilidades (id, nombre) VALUES (384, 'Wimp Out');
INSERT INTO habilidades (id, nombre) VALUES (385, 'Wonder Guard');
INSERT INTO habilidades (id, nombre) VALUES (386, 'Zen Mode');

-- migration:down 

 DELETE FROM habilidades;